services:
  - type: web
    name: chatapp
    env: node
    buildCommand: |
      npm install
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: npm start
    buildFilter:
      paths:
        - frontend/**
        - Backend/**
        - package.json
        - render.yaml
    envVars:
      - key: NODE_VERSION
        value: 20
